import Header from "@/features/layout/Header";
import "@/styles/globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Inter } from "next/font/google";
import Provider from "@/utils/Providers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App Make Project",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body className={`font-sans ${inter.variable}`}>
        <Header />
        <div className="mx-auto mt-6 w-[90%] max-w-[1100px]">
          <Provider>{children}</Provider>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
